### ISSUE TITLE
Fix ValueError: string argument should contain only ASCII characters; on PowerShell

### ISSUE THREAD

**Issue by salsburj** [imsweb/cconf#1]
Interestingly, the following two commands (genkey followed by encrypt) are working in cmd, but not PowerShell.

```
> cconf genkey > a.key
> cconf encrypt --keyfile a.key apples
Traceback (most recent call last):
  File "c:\program files\python38\lib\base64.py", line 37, in _bytes_from_decode_data
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "...\cconf.exe\__main__.py", line 7, in <module>
  File "...\cconf\cli.py", line 172, in main
    execute(**vars(options))
  File "...\cconf\cli.py", line 161, in execute
    encrypt(config, **options)
  File "...\cconf\cli.py", line 69, in encrypt
    log(cipher.encrypt(options["value"][0]))
  File "...\cconf\ciphers.py", line 82, in encrypt
    self._load_keys()
  File "...\cconf\ciphers.py", line 77, in _load_keys
    self._keys = read_keys(fileobj)
  File "...\cconf\ciphers.py", line 30, in read_keys
    fernets.append(Fernet(key))
  File "...\cryptography\fernet.py", line 33, in __init__
    key = base64.urlsafe_b64decode(key)
  File "c:\program files\python38\lib\base64.py", line 131, in urlsafe_b64decode
    s = _bytes_from_decode_data(s)
  File "c:\program files\python38\lib\base64.py", line 39, in _bytes_from_decode_data
    raise ValueError('string argument should contain only ASCII characters')
ValueError: string argument should contain only ASCII characters
```

**Comment by salsburj** [comment]
As it turns out, this may not be a PowerShell vs cmd issue, but rather an issue with the `genkey` command.

We have found that `genkey` sometimes works and sometimes does not. We have a hunch that it may sometimes generate some character that's causing this error.

**Comment by jhunterc15** [comment]
This happened to Elia and I as well. It seems to be because PowerShell defaults to unicode and adds the utf-16 bom. The bom is not valid ASCII which causes that error.

**Comment by elia-deppe** [comment]
When generating the key in Powershell, using the command `cconf genkey > name_cconf.key`, Powershell will write the key in Unicode as opposed to ASCII. We can see this by inspecting the file with a hex editor:

![hex](https://github.com/imsweb/cconf/assets/120408678/147bc2df-d318-465c-b272-b8be7623734f)

The start of the file contains FF FE, is the Unicode BOM as Josh posted above. This also explains why null characters (00) are placed after every character as Unicode's default encoding is 16 bit. Looking at the ![docs for PowerShell](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.4#character-encoding-in-windows-powershell), we see this is confirmed as well:

> - `Out-File` and the redirection operators `>` and `>>` create UTF-16LE, which notably differs from `Set-Content` and `Add-Content`.

If we utilize the `Set-Content` command like so: `Set-Content -Path .\fake.key -value (cconf genkey)`, our output is in good ol' ASCII. I doubt most people would want to write that instead of the simply using the `>` operator though.

![hex2](https://github.com/imsweb/cconf/assets/120408678/a21184dd-2e1e-4d4b-b17f-63e2edb0e1f4)

A user can update their default encoding: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.4#changing-the-default-encoding

Adding `$PSDefaultParameterValues['Out-File:Encoding'] = 'ascii'` to my Powershell Profile causes our output to go back to normal when using `cconf genkey > name_cconf.key`:

![hex3](https://github.com/imsweb/cconf/assets/120408678/39118505-fcc8-4a3d-bcc8-42533d5a7cd8)

I think this is less a problem with cconf, and more a problem with Powershell configuration.

**Comment by dcwatson** [comment]
How about an `-o` option for specifying a filename, e.g. `cconf genkey -o secret.key`? Then we can bypass the issue of `>` writing UTF-16.
